### ISSUE TITLE
Cannot launch the app: Cannot find module npm

### ISSUE THREAD

**Issue by Atinux** [electronuxt/electronuxt-starter#1]
Hey there,

Great job on making an Electron app with Nuxt.js

Right now, I cannot launch the app, I have this following error:

```
App threw an error during load
Error: Cannot find module 'npm'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/Atinux/Projets/nuxt/electronuxt-starter/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Atinux/Projets/nuxt/electronuxt-starter/main.js:29:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

This is really weird since of course I have npm in my console (version `4.2.0`), any idea?

**Comment by detrohutt** [comment]
Hmm... you're on a Mac right? I've made several changes since checking it with my Mac. I'll check it out now.

**Comment by Atinux** [comment]
Yep I am on a Mac, I'll try to investigate the issue as well!

**Comment by detrohutt** [comment]
Ah, it's broken for me too.. good catch! Investigating now.

**Comment by detrohutt** [comment]
I think I got it. Let me know if it's still messed up.

**Comment by Atinux** [comment]
Hey @detrohutt 

Please test my repository: https://github.com/Atinux/electronuxt

As you can see, I directly import **nuxt** inside so HMR works and also production mode. I let you try and if you like it, merge it inside your project so I can remove my temporary repository 👍

**Comment by detrohutt** [comment]
@Atinux Thank you!!! I just glanced over it and it looks a lot simpler than what I ended up with lol. I've been awake for over 24 hours so I'll have to check it out after I get some sleep. I went ahead and pulled it into a separate branch on my repo so you can delete yours whenever.
